;====================================================================
; Main.asm file generated by New Project wizard
;
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
;-----------------------------------------------------------
;实验示例程序                                              |
;                                                        |
;功能：读取开关量的状态取反后送到LED显示                  	 |
;74LS244带有8位拨位开关，地址为80H or 82H or 84H or 86H   	 |
;74LS273带有8个发光二极管，地址为88H or 8AH or 8CH or 8EH 	 |
;                                                        |
;-----------------------------------------------------------
		.MODEL	SMALL			; 设定8086汇编程序使用Small model
		.8086				; 设定采用8086汇编指令集
;-----------------------------------------------------------
;	符号定义                                               |
;-----------------------------------------------------------
PortIn	EQU	80h	;定义输入端口号
PortOut	EQU	88h	;定义输出端口号
;-----------------------------------------------------------
;	定义堆栈段                                             |
;-----------------------------------------------------------
		.stack 100h				; 定义256字节容量的堆栈

;-----------------------------------------------------------
;	定义数据段                                             |
;-----------------------------------------------------------
		.data					; 定义数据段

;-----------------------------------------------------------
;	定义代码段                                             |
;-----------------------------------------------------------
		.code						; Code segment definition
		.startup					; 定义汇编程序执行入口点
;
;以下开始放置用户指令代码

;-----------------------------------------------------------
;主程序部分,读取开关量状态取反后送显示                     |
;-----------------------------------------------------------

START:
		MOV AL,36H				;初始状态
		OUT PortOut,AL
AGAIN:		
		                                        ;状态1南北绿灯；东西红灯
		MOV AL,33H 				
		OUT 88H,AL         
		CALL DELAY2
		
		;状态2南北绿灯闪转黄灯；东西红灯
		MOV AL,37H 				;绿灯闪，灭
		OUT 88H,AL
		CALL DELAY1
		
		MOV AL,33H  				;绿灯闪，亮
		OUT 88H,AL
		CALL DELAY1
		
		MOV AL,37H
		OUT 88H,AL
		CALL DELAY1
		
		MOV AL,33H 
		OUT 88H,AL
		CALL DELAY1
		
		MOV AL,35H 				;绿灯转黄灯
		OUT 88H,AL
		CALL DELAY2
		
		;状态3南北红灯；东西绿灯
		MOV AL,1EH 
		OUT 88H,AL
		CALL DELAY2
		
		;南北红灯闪转黄灯；东西绿灯
		MOV AL,3EH 				;绿灯闪，灭
		OUT 88H,AL
		CALL DELAY1
		
		MOV AL,1EH 				;绿灯闪，亮
		OUT 88H,AL
		CALL DELAY1
		
		MOV AL,3EH
		OUT 88H,AL
		CALL DELAY1
		
		MOV AL,1EH 
		OUT 88H,AL
		CALL DELAY1
		
		MOV AL,2EH 				;绿灯转黄灯
		OUT 88H,AL
		CALL DELAY2
		
		JMP AGAIN
		
DELAY1 PROC FAR 					;短延时，转换为黄灯
		MOV CX,1000H				;计数器进cx
LOOP1:
		DEC CX					;CX递减
		JNZ LOOP1
		
		RET
DELAY1 ENDP

DELAY2 PROC FAR						;长延时，状态切换
	        MOV CX,3FFFH
LOOP2: 
	        DEC CX
	        JNZ LOOP2
		
	        RET
DELAY2 ENDP
	       
		END					;指示汇编程序结束编译